FROM nginx:latest
EXPOSE 80 443
#COPY nginx.conf /etc/nginx/nginx.conf
#COPY dhparam-2048.pem /etc/letsencrypt/live/dhparam-2048.pem
#COPY nginx-selfsigned.crt /etc/nginx/nginx-selfsigned.crt
#COPY nginx-selfsigned.key /etc/nginx/nginx-selfsigned.key